### PR TITLE
fix: Use FontMatrix to scale Type3 font metrics

### LINKED ISSUE #99: Wrong text output
[Stafford.County.-.VA.Zoning.Ordinance.pdf](https://github.com/user-attachments/files/18687439/Stafford.County.-.VA.Zoning.Ordinance.pdf)

### PR DESCRIPTION
**Pull request by dhdaines**
`get_unit` didn't do anything useful, but also it isn't sufficient to just scale the font size in the case of Type3 fonts - the font matrix can (and often does) flip the axes of the glyph space as well as rescaling it, so we need to take this into account when calculating ascent and descent.

Fixes #99

### CODE REVIEW

**Comment by PeterStaar-IBM** [comment]
@dhdaines Awesome work, I can only say: big thanks for this fix and the additional test case!

A few little comments:

1. would it be possible to avoid `==` and `!=` operations of the components of the font-matrix. It might be nice to set a boolean variable (maybe `is_font_type_3`?) in the function `init_font_matrix()`. I am just a bit worried that on different systems the `!=` on doubles might a buggy.
2. Can you always put `{}` around what follows the if-statements
3. Could you also check that the `result` vector from the font-matrix is of length 6 (line: 891)?

Again big thanks and well done!

File: src/v2/pdf_resources/page_font.h [hunk 1]
```diff
@@ -891,6 +879,37 @@ namespace pdflib
...
+  {
+    LOG_S(INFO) << __FUNCTION__;// << "\t" << json_font.dump(2);
+
+    std::vector<std::string> keys_0 = {"/FontMatrix"};
+
+    if(utils::json::has(keys_0, json_font))
+      {
+        //assert(subtype==TYPE_3);
+        auto result = utils::json::get(keys_0, json_font);
+
```
Comment (PeterStaar-IBM) [inline src/v2/pdf_resources/page_font.h:892]: Let's check that result has a size of 6 before we continue

File: src/v2/pdf_resources/page_font.h [hunk 2]
```diff
@@ -891,6 +879,37 @@ namespace pdflib
...
+          {
+            font_matrix[d] = result[d].get<double>();
+          }
+      }
+    else
+      {
+        LOG_S(INFO) << "using default font-matrix";
+        font_matrix = {0.001, 0, 0, 0.001, 0, 0};
+      }
+
```
Comment (PeterStaar-IBM) [inline src/v2/pdf_resources/page_font.h:903]: Let's set an internal boolean flag here which analyses the font-matrix and avoids us to do `!=` downstream.

File: src/v2/pdf_resources/page_font.h [hunk 3]
```diff
@@ -1166,7 +1185,15 @@ namespace pdflib
         {
           LOG_S(WARNING) << "'xheight' was not explicitely defined ...";
         }
-    }    
+    }
+
+    if (font_matrix[3] != 0.001)
```
Comment (PeterStaar-IBM) [inline src/v2/pdf_resources/page_font.h:1190]: replace this inequality with the newly introduced boolean flag.

File: src/v2/pdf_resources/page_font.h [hunk 4]
```diff
@@ -1305,6 +1332,8 @@ namespace pdflib
 	  }
 	
         numb_to_widths[ind] = values[cnt++];
+        if (font_matrix[0] != 0.001)
```
Comment (PeterStaar-IBM) [inline src/v2/pdf_resources/page_font.h:1335]: replace this inequality with the newly introduced boolean flag.

File: src/v2/pdf_resources/page_font.h [hunk 5]
```diff
@@ -1305,6 +1332,8 @@ namespace pdflib
...
+          numb_to_widths[ind] *= font_matrix[0] * 1000.0;
```
Comment (PeterStaar-IBM) [inline src/v2/pdf_resources/page_font.h:1336]: Add `{ ... }` around

File: src/v2/pdf_resources/page_font.h [hunk 6]
```diff
@@ -1383,6 +1412,8 @@ namespace pdflib
               {
 		//LOG_S(WARNING) << "\t" << id << " -> " << w;
                 numb_to_widths[id] = w;
+                if (font_matrix[0] != 0.001)
```
Comment (PeterStaar-IBM) [inline src/v2/pdf_resources/page_font.h:1415]: Replace this inequality with the newly introduced boolean flag.

File: src/v2/pdf_resources/page_font.h [hunk 7]
```diff
@@ -1404,6 +1435,8 @@ namespace pdflib
 		//LOG_S(WARNING) << "\t" << beg+k  << " -> " << w[k];
 
                 numb_to_widths[beg+k] = w[k];
+                if (font_matrix[0] != 0.001)
```
Comment (PeterStaar-IBM) [inline src/v2/pdf_resources/page_font.h:1438]: Replace this inequality with the newly introduced boolean flag.

File: src/v2/pdf_resources/page_font.h [hunk 8]
```diff
@@ -1383,6 +1412,8 @@ namespace pdflib
               {
 		//LOG_S(WARNING) << "\t" << id << " -> " << w;
                 numb_to_widths[id] = w;
+                if (font_matrix[0] != 0.001)
+                  numb_to_widths[id] *= font_matrix[0] * 1000.0;
```
Comment (PeterStaar-IBM) [inline src/v2/pdf_resources/page_font.h:1416]: Add { ... } around

File: src/v2/pdf_resources/page_font.h [hunk 9]
```diff
@@ -1404,6 +1435,8 @@ namespace pdflib
 		//LOG_S(WARNING) << "\t" << beg+k  << " -> " << w[k];
 
                 numb_to_widths[beg+k] = w[k];
+                if (font_matrix[0] != 0.001)
+                  numb_to_widths[beg+k] *= font_matrix[0] * 1000.0;
```
Comment (PeterStaar-IBM) [inline src/v2/pdf_resources/page_font.h:1439]: Add { ... } around

**Review by PeterStaar-IBM — CHANGES_REQUESTED** [review]

**Comment by dhdaines** [comment]
> 1. would it be possible to avoid `==` and `!=` operations of the components of the font-matrix. It might be nice to set a boolean variable (maybe `is_font_type_3`?) in the function `init_font_matrix()`. I am just a bit worried that on different systems the `!=` on doubles might a buggy.

Ah, indeed - I wasn't worried about it because it is checking for the default case where we have explicitly set the value to the constant 0.001 elsewhere, but you're right, that isn't a comparison that is reliably true on floating-point values.

> 2. Can you always put `{}` around what follows the if-statements
> 3. Could you also check that the `result` vector from the font-matrix is of length 6 (line: 891)?

Yes, of course ... I'm not familiar with the JSON library in question or its API...

File: src/v2/pdf_resources/page_font.h (hunk 1 above)
Comment (dhdaines) [reply src/v2/pdf_resources/page_font.h:892]: Sure, I will also add similar checks in `init_font_bbox`

**Comment by PeterStaar-IBM** [comment]
> > 1. would it be possible to avoid `==` and `!=` operations of the components of the font-matrix. It might be nice to set a boolean variable (maybe `is_font_type_3`?) in the function `init_font_matrix()`. I am just a bit worried that on different systems the `!=` on doubles might a buggy.
> 
> Ah, indeed - I wasn't worried about it because it is checking for the default case where we have explicitly set the value to the constant 0.001 elsewhere, but you're right, that isn't a comparison that is reliably true on floating-point values.

Yes, I have been burnt a few too many times!

> > 2. Can you always put `{}` around what follows the if-statements
> > 3. Could you also check that the `result` vector from the font-matrix is of length 6 (line: 891)?
> 
> Yes, of course ... I'm not familiar with the JSON library in question or its API...

No worries! For the array, just use,

```
if (j.is_array() && j.size() == 6) {
    // it's an array and has size 6
} 
else {
   // Let's do some error message here
}
```

=> Again, big thanks and looking forward merging this in!

**Comment by dhdaines** [comment]
Should be ready now!

**Comment by PeterStaar-IBM** [comment]
Very nice, I will take it from here to get it all merged. Let's verify all the tests pass and we should be good to go!

**Comment by dolfim-ibm** [comment]
For reference, here is the usage of this PR in the Docling tests: https://github.com/docling-project/docling/pull/1326 (it compares against the docling-parse v4 test updates).

✅  The only difference is tiny diff in a bbox.

**Review by dolfim-ibm — APPROVED** [review]
lgtm

**Review by PeterStaar-IBM — APPROVED** [review]
awesome work, deserves 🎖️ !
